name: go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go_version: [ '1.20' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - name: Use golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.1

      - name: Run unit tests
        run: go test -race ./...
